### ISSUE TITLE
RHOB file format

### ISSUE THREAD

**Issue by Selfiekraken** [VASPsol/VASPsol#1]
Hello developers, I'm having trouble openning the RHOB file with VESTA 
for visualization of bound charge.
The related INCAR tags was 
LSOL   =  .TRUE.
EB_K   =  78.4
TAU    =  0
LRHOB  =  .TRUE.
The format of RHOB file seemed just like that of CHGCAR, but when I load it into
VESTA it report: This file type is not supported!
May you suggest any possible reason and solution to this?
Thank you!
[RHOB.zip](https://github.com/VASPsol/VASPsol/files/14013513/RHOB.zip)

**Comment by TTsangSC** [comment]
Hi, I'm not with the devs, but if VESTA is hesitant to open a VASP file just try to rename it to `<something>.vasp`. 
This should signal to the VESTA that despite the file's not being the usual `CHGCAR`, `CHG`, `LOCPOT`, etc., it is still safe to try and read it as generic volumetric data. 
Just tested on my Mac, and VESTA did initially refuse to read an `RHOB` file, only opening it when I renamed it to `RHOB.vasp`.
