### ISSUE TITLE
Question about the absoulute value of standard hydrogen electrode potential

### ISSUE THREAD

**Issue by nkuhuxu** [VASPsol/VASPsol#4]
Hi developers,

The absolute electron chemical potential of the SHE mentioned in the article (https://doi.org/10.1063/5.0176308) is reported as -4.47. However, I noticed that in the README file, a different value of -4.57 is used. Could you please clarify the reason?

**Comment by craigplaisance** [comment]
The value in the paper had a typo, you should use the value here (-4.57 eV)

**Comment by craigplaisance** [comment]
... although ideally, you should compute this yourself as it depends on the functional you are using. We computed -4.57 eV with the BEEF-vdW functional. We get -4.04 eV using the PBE functional.
