### ISSUE TITLE
Feature request: compiling VASPsol++ with gfortran

### ISSUE THREAD

**Issue by emilyviolet** [VASPsol/VASPsol#5]
Hi,

Asis  mentioned in the "Installation" section of the README, VASPsol only works with the Intel Fortran compiler (specifically, the "Classic" `ifort` compiler, not the newer LLVM-based `ifx`), due to some Intel-specific idioms. It currently does not compile with the GNU or Cray Fortran compilers, which are the only two supported on the HPC cluster where I work, meaning VASPsol++ is currently not usable on our systems.

Is porting VASPsol++ to work with other Fortran compilers something that's in the development plans? If you don't have plans already underway, then I'd be happy to take a crack at it. I've done some preliminary development and it looks feasible to get it to compile with gfortran, so I'd be happy to work with you on this if it's of interest.

**Comment by craigplaisance** [comment]
I have a version that works with another compiler (gfortran if i remember correctly). If you email me, I can send you a copy.
