### ISSUE TITLE
The change of EFERMI_ref in VASPsol++ has no effect on the calculation results

### ISSUE THREAD

**Issue by OTTHao** [VASPsol/VASPsol#6]
Dear developers:
As shown in the question, I performed constant potential simulation calculations in Vaspsol++using the README method. However, when I added the following parameters to INCAR, there was no significant change in the calculation results, except for the effect of solvation. I adjusted the value of EFERMIref, but it did not affect the final result. I want to know where the problem is?
This is my INCAR file:

SYSTEM = relax
ISTART = 0
NPAR = 4
LREAL = Auto
ISPIN = 2
PREC = Accurate

LSOL = .TRUE.
ISOL = 2
capacitance_init = 2
C_MOLAR = 1.0 # set to the electrolyte concentration in mol/L
R_ION = 4.0 # set to the ionic radius in Angstrom
EFERMI_ref = -4.07 # set to the electron chemical potential in eV

IBRION = 2
ISIF = 2
EDIFFG =-2E-2
POTIM = 0.05
NSW = 0

ENCUT = 520
ISMEAR = 0
SIGMA = 0.05
EDIFF = 1E-5

plus：The code was successfully compiled, when I set up LVHAR = .TRUE. , the related files were existed

**Comment by craigplaisance** [comment]
The problem is that you are setting NSW to 0. The charge is updated during the geometry optimization, so if you run a static calculation then it won't work

**Comment by OTTHao** [comment]
> The problem is that you are setting NSW to 0. The charge is updated during the geometry optimization, so if you run a static calculation then it won't work

It works, thanks a lot!!!
